services:
  server:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__webhook__ALLOWED_HOST_LIST=jenkins
      - GITEA__webhook__SKIP_TLS_VERIFY=true
      - GITEA__server__ROOT_URL=http://gitea:3000/
    volumes:
      - ./.volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  postgres-dev:
    image: postgres:15
    container_name: postgres-dev
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  jenkins:
    #image: jenkins/jenkins:latest
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    depends_on:
      - postgres-dev
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dorg.eclipse.jetty.server.Request.maxFormContentSize=1000000 -Dorg.eclipse.jetty.server.Request.maxFormKeys=10000
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./.volumes/jenkins:/var/jenkins_home
      - ./.volumes/jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
      - "50000:50000"
