services:
  server:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__webhook__ALLOWED_HOST_LIST=jenkins
      - GITEA__webhook__SKIP_TLS_VERIFY=true
      - GITEA__server__ROOT_URL=http://gitea:3000/
    volumes:
      - ./.volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  jenkins:
    #image: jenkins/jenkins:latest
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./.volumes/jenkins:/var/jenkins_home
      - ./.volumes/jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
      - "50000:50000"
