"""
Model Validator for comparing ETL source models with database schemas.

Validates that the ETL framework's source model (dimensions and facts)
matches the target database schema defined in HCL files (generated by dbci-tools).
"""

from pathlib import Path
from typing import Dict, List, Set, Tuple
from dataclasses import dataclass
from enum import Enum

from dagster_etl_framework.hcl_parser import HclParser, HclTable
from dagster_etl_framework.source_model import SourceModel, Dimension, Fact, SourceFieldType


class ValidationSeverity(str, Enum):
    """Severity level for validation issues."""
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"


@dataclass
class ValidationIssue:
    """Represents a validation issue found during comparison."""
    severity: ValidationSeverity
    table_name: str
    column_name: str = None
    message: str = ""
    
    def __str__(self):
        location = f"{self.table_name}"
        if self.column_name:
            location += f".{self.column_name}"
        return f"[{self.severity.value}] {location}: {self.message}"


@dataclass
class ValidationResult:
    """Results from model validation."""
    issues: List[ValidationIssue]
    tables_validated: int = 0
    columns_validated: int = 0
    
    @property
    def has_errors(self) -> bool:
        """Check if any errors were found."""
        return any(issue.severity == ValidationSeverity.ERROR for issue in self.issues)
    
    @property
    def has_warnings(self) -> bool:
        """Check if any warnings were found."""
        return any(issue.severity == ValidationSeverity.WARNING for issue in self.issues)
    
    def get_errors(self) -> List[ValidationIssue]:
        """Get all error-level issues."""
        return [i for i in self.issues if i.severity == ValidationSeverity.ERROR]
    
    def get_warnings(self) -> List[ValidationIssue]:
        """Get all warning-level issues."""
        return [i for i in self.issues if i.severity == ValidationSeverity.WARNING]
    
    def get_infos(self) -> List[ValidationIssue]:
        """Get all info-level issues."""
        return [i for i in self.issues if i.severity == ValidationSeverity.INFO]


class ModelValidator:
    """
    Validates ETL source models against database schemas.
    
    Compares the analytical model (dimensions and facts) defined in the
    source_model.yaml against the actual database schema in HCL format.
    """
    
    # System columns that are auto-generated and not in source model
    SYSTEM_COLUMNS = {
        'dim_customer_sk', 'dim_product_sk', 'dim_date_id',  # Surrogate keys
        'version', 'effective_from', 'effective_to', 'is_current',  # SCD fields
        'created_at', 'updated_at'  # Audit fields
    }
    
    # Date dimension is generated by the framework and not defined in source model
    DATE_DIMENSION_TABLE = 't_dim_date'
    
    def __init__(self, source_model: SourceModel, hcl_file: Path):
        """
        Initialize validator.
        
        Args:
            source_model: Parsed source model with dimensions and facts
            hcl_file: Path to HCL schema file from dbci-tools
        """
        self.source_model = source_model
        self.hcl_file = hcl_file
        self.issues: List[ValidationIssue] = []
        
    def validate(self) -> ValidationResult:
        """
        Run complete validation.
        
        Returns:
            ValidationResult with all issues found
        """
        self.issues = []
        
        # Parse HCL schema
        parser = HclParser(self.hcl_file)
        hcl_tables = parser.parse()
        
        tables_count = 0
        columns_count = 0
        
        # Validate dimensions
        for dim_name, dimension in self.source_model.dimensions.items():
            hcl_table_name = f"t_dim_{dim_name}"
            if hcl_table_name in hcl_tables:
                col_count = self._validate_dimension(dim_name, dimension, hcl_tables[hcl_table_name])
                tables_count += 1
                columns_count += col_count
            else:
                self.issues.append(ValidationIssue(
                    severity=ValidationSeverity.ERROR,
                    table_name=hcl_table_name,
                    message=f"Dimension '{dim_name}' defined in source model but table not found in HCL schema"
                ))
        
        # Validate facts
        for fact_name, fact in self.source_model.facts.items():
            hcl_table_name = f"t_fact_{fact_name}"
            if hcl_table_name in hcl_tables:
                col_count = self._validate_fact(fact_name, fact, hcl_tables[hcl_table_name])
                tables_count += 1
                columns_count += col_count
            else:
                self.issues.append(ValidationIssue(
                    severity=ValidationSeverity.ERROR,
                    table_name=hcl_table_name,
                    message=f"Fact '{fact_name}' defined in source model but table not found in HCL schema"
                ))
        
        # Check for extra tables in HCL not in source model
        expected_tables = set()
        for dim_name in self.source_model.dimensions.keys():
            expected_tables.add(f"t_dim_{dim_name}")
        for fact_name in self.source_model.facts.keys():
            expected_tables.add(f"t_fact_{fact_name}")
        
        # Add date dimension to expected tables (it's auto-generated)
        expected_tables.add(self.DATE_DIMENSION_TABLE)
        
        for table_name in hcl_tables.keys():
            if table_name not in expected_tables:
                self.issues.append(ValidationIssue(
                    severity=ValidationSeverity.WARNING,
                    table_name=table_name,
                    message=f"Table found in HCL schema but not defined in source model"
                ))
        
        return ValidationResult(
            issues=self.issues,
            tables_validated=tables_count,
            columns_validated=columns_count
        )
    
    def _validate_dimension(self, dim_name: str, dimension: Dimension, hcl_table: HclTable) -> int:
        """
        Validate a dimension against its HCL table.
        
        Returns:
            Number of columns validated
        """
        # Collect all expected columns from source model
        expected_columns = {}
        
        for source_name, dim_source in dimension.sources.items():
            for field in dim_source.fields:
                # Use alias if provided, otherwise use field name
                column_name = field.alias if field.alias else field.name
                expected_columns[column_name] = (field, source_name)
        
        # Add extract_date which is always present
        expected_columns['extract_date'] = (None, 'system')
        
        # Check that all expected columns exist in HCL
        for col_name, (field, source_name) in expected_columns.items():
            if col_name not in hcl_table.columns:
                self.issues.append(ValidationIssue(
                    severity=ValidationSeverity.ERROR,
                    table_name=hcl_table.name,
                    column_name=col_name,
                    message=f"Column defined in source model (from '{source_name}') but missing in HCL schema"
                ))
        
        # Check for unexpected columns in HCL (excluding system columns)
        for col_name in hcl_table.columns.keys():
            if col_name not in expected_columns and col_name not in self.SYSTEM_COLUMNS:
                self.issues.append(ValidationIssue(
                    severity=ValidationSeverity.WARNING,
                    table_name=hcl_table.name,
                    column_name=col_name,
                    message=f"Column found in HCL schema but not defined in source model"
                ))
        
        return len(expected_columns)
    
    def _validate_fact(self, fact_name: str, fact: Fact, hcl_table: HclTable) -> int:
        """
        Validate a fact table against its HCL table.
        
        Returns:
            Number of columns validated
        """
        # Collect all expected columns from source model
        expected_columns = {}
        
        for source_name, fact_source in fact.sources.items():
            for field in fact_source.fields:
                # Use alias if provided, otherwise use field name
                column_name = field.alias if field.alias else field.name
                expected_columns[column_name] = (field, source_name)
        
        # Add extract_date which is always present
        expected_columns['extract_date'] = (None, 'system')
        
        # Check that all expected columns exist in HCL
        for col_name, (field, source_name) in expected_columns.items():
            if col_name not in hcl_table.columns:
                self.issues.append(ValidationIssue(
                    severity=ValidationSeverity.ERROR,
                    table_name=hcl_table.name,
                    column_name=col_name,
                    message=f"Column defined in source model (from '{source_name}') but missing in HCL schema"
                ))
        
        # Check for unexpected columns in HCL (excluding system columns)
        for col_name in hcl_table.columns.keys():
            if col_name not in expected_columns and col_name not in self.SYSTEM_COLUMNS:
                self.issues.append(ValidationIssue(
                    severity=ValidationSeverity.WARNING,
                    table_name=hcl_table.name,
                    column_name=col_name,
                    message=f"Column found in HCL schema but not defined in source model"
                ))
        
        return len(expected_columns)


def validate_model(source_model: SourceModel, hcl_file: Path) -> ValidationResult:
    """
    Convenience function to validate a source model against an HCL schema.
    
    Args:
        source_model: The ETL source model to validate
        hcl_file: Path to the HCL schema file
        
    Returns:
        ValidationResult with all issues found
        
    Example:
        from dagster_etl_framework import load_source_model, validate_model
        
        model = load_source_model("demo_etl/source_model.yaml")
        result = validate_model(model, Path("../demo-dw/target/schema.hcl"))
        
        if result.has_errors:
            print("Validation failed!")
            for error in result.get_errors():
                print(f"  {error}")
    """
    validator = ModelValidator(source_model, hcl_file)
    return validator.validate()
