import jenkins.model.*
import hudson.security.*

// Auto-generated by devops_tools

def instance = Jenkins.getInstance()

def adminUser = "$user"
def adminPass = "$password"

println "--> creating admin user $user"

def hudsonRealm = new HudsonPrivateSecurityRealm(false)
def user = hudsonRealm.createAccount(adminUser, adminPass)
instance.setSecurityRealm(hudsonRealm)

def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
strategy.setAllowAnonymousRead(false)
instance.setAuthorizationStrategy(strategy)

instance.setInstallState(jenkins.install.InstallState.INITIAL_SETUP_COMPLETED)
instance.save()